name: sac_slide_puzzle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  google_fonts: ^2.3.1
  gap: ^2.0.0
  universal_platform: ^1.0.0+1
  http: ^0.13.4
  just_audio: ^0.9.18
  just_audio_libwinmedia: ^0.0.4
  url_launcher: ^6.0.20
  file_picker: ^4.3.3
  crop_your_image: ^0.6.0+1
  streaming_shared_preferences: ^2.0.0
  path_provider: ^2.0.8
  username_generator: ^1.3.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  confetti: ^0.6.0
  rive: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/images/gallery/
    - assets/images/air/
    - assets/images/water/
    - assets/images/earth/
    - assets/images/fire/
    - assets/rive/
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
          weight: 400